Repository DXgovernance/dxdao-contracts, pull requests merged in 2022-04, with the labels that each got.

#104 PermissionRegistry Fixes
  contracts/dxvote/PermissionRegistry.sol
  test/dxvote/PermissionRegistry.js
Labels: bug, Intermediate Audit Report

#106 Remove parameter and use msg.sender for signatures
  contracts/dxvote/DXDVotingMachine.sol
  contracts/hardhat-dependency-compiler/.hardhat-dependency-compiler
  contracts/hardhat-dependency-compiler/@openzeppelin/contracts/proxy/transparent/ProxyAdmin.sol
  contracts/hardhat-dependency-compiler/@openzeppelin/contracts/proxy/transparent/TransparentUpgradeableProxy.sol
  contracts/hardhat-dependency-compiler/@realitio/realitio-contracts/truffle/contracts/Realitio.sol
Labels: bug, Intermediate Audit Report

#103 Allow anyone to call shareSignedVote
  contracts/dxvote/DXDVotingMachine.sol
  package.json
  test/dxvote/DXDVotingMachine.js
Labels: enhancement, Intermediate Audit Report

#102 Feature/enforced binary guild implementation
  contracts/erc20guild/implementations/EnforcedBinaryGuild.sol
  test/erc20guild/implementations/EnforcedBinaryGuild.js
Labels: enhancement

#93 Fix continuous integration tests #54
  .github/workflows/lint.yml
  .gitignore
  contracts/dxvote/DXDVotingMachine.sol
  contracts/dxvote/WalletScheme.sol
  contracts/dxvote/utils/DXDVestingFactory.sol
  contracts/dxvote/utils/DXdaoNFT.sol
  contracts/erc20guild/ERC20Guild.sol
  contracts/erc20guild/implementations/GuardedERC20Guild.sol
  contracts/erc20guild/implementations/MigratableERC20Guild.sol
  contracts/erc20guild/implementations/SnapshotERC20Guild.sol
  contracts/erc20guild/implementations/SnapshotRepERC20Guild.sol
  contracts/utils/ERC20/ERC20SnapshotRep.sol
  contracts/utils/ERC20/ERC20TokenVesting.sol
  contracts/utils/TokenVault.sol
  package.json
  scripts/installSlither.sh
  scripts/slither.sh
  slither.config.json
  yarn.lock
Labels: bug, Intermediate Audit Report

#124 Workflow does not trigger on external PR
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: bug

#119 Allow multiple options proposals, check decision before vote
  contracts/dxvote/DXDVotingMachine.sol
  test/dxvote/DXDVotingMachine.js
  test/helpers/index.js
Labels: Intermediate Audit Report

#130 feat: Add EnforcedBinarySnapshotERC20Guild implementation.
  contracts/erc20guild/implementations/EnforcedBinarySnapshotERC20Guild.sol
  test/erc20guild/implementations/EnforcedBinarySnapshotERC20Guild.js
Labels: enhancement

#121 Fully test the voting machine
  contracts/dxvote/DXDVotingMachine.sol
  test/daostack/ContributionRewards.js
  test/daostack/Schemeregistrar.js
  test/dxdao/dxdao.js
  test/dxvote/DXDVestingFactory.js
  test/dxvote/DXDVotingMachine.js
  test/dxvote/PermissionRegistry.js
  test/dxvote/Utils.js
  test/dxvote/WalletScheme.js
  test/erc20guild/ERC20Guild.js
  test/erc20guild/implementations/DXDGuild.js
  test/erc20guild/implementations/EnforcedBinaryGuild.js
  test/erc20guild/implementations/EnforcedBinarySnapshotERC20Guild.js
  test/erc20guild/implementations/MigratableERC20Guild.js
  test/erc20guild/implementations/SnapshotERC2Guild.js
  test/erc20guild/implementations/SnapshotRepERC20.js
  test/erc20guild/utils/GuildRegistry.js
  test/helpers/constants.js
  test/helpers/guild.js
  test/helpers/index.js
  test/helpers/walletScheme.js
  test/omen/OMNGuild.js
Labels: Intermediate Audit Report
