Repository DXgovernance/dxdao-contracts, pull requests merged in 2023-02, with the labels that each got.

#291 refactor: allow gas refunds for contracts
  contracts/erc20guild/BaseERC20Guild.sol
  test/erc20guild/ERC20Guild.js
Labels: guilds, v2.0

#308 DXD staking and influence contracts
  contracts/dao/AccountSnapshot.sol
  contracts/dao/DXDInfluence.sol
  contracts/dao/DXDStake.sol
  contracts/test/VotingPowerMock.sol
  package.json
  test/dao/DXDStake.js
  yarn.lock
Labels: v2.1

#305 Add sepolia to hardhat config
  hardhat.config.js
Labels: v2.0

#311 Feat/non retroactive formula changes
  contracts/dao/AccountSnapshot.sol
  contracts/dao/DXDInfluence.sol
  test/dao/DXDStake.js
Labels: v2.1

#312 refactor: optimize storage and snapshots
  contracts/dao/AccountSnapshot.sol
  contracts/dao/DXDInfluence.sol
  contracts/dao/DXDStake.sol
  contracts/utils/ERC20/OptimizedERC20SnapshotUpgradeable.sol
  test/dao/DXDStake.js
Labels: v2.1

#289 Feat/zodiac guilds
  contracts/erc20guild/implementations/PermissionRegistryModule.sol
  contracts/erc20guild/implementations/ZodiacERC20Guild.sol
  contracts/test/ModuleProxyFactory.sol
  contracts/test/MultiSend.sol
  contracts/test/TestAvatar.sol
  contracts/utils/IPermissionRegistry.sol
  hardhat.config.js
  package.json
  test/erc20guild/implementations/PermissionRegistryModule.js
  test/erc20guild/implementations/ZodiacERC20Guild.js
  yarn.lock
Labels: guilds, v2.1
